tasks:
  - init: |
      git clone https://github.com/flutter/flutter.git -b stable ~/flutter
      echo "export PATH=\$PATH:~/flutter/bin" >> ~/.bashrc
      flutter doctor
ports:
  - port: 8080
    onOpen: open-preview
