name: Run ARCore Emulator

on:
  push:
    branches:
      - main

jobs:
  setup-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Installer Android SDK Command-line Tools
      - name: Install Android SDK Tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator" >> $GITHUB_ENV

      # 3. Accepter les licences Android
      - name: Accept Android SDK Licenses
        run: |
          source $GITHUB_ENV
          yes | sdkmanager --licenses

      # 4. Installer les composants nécessaires pour ARCore
      - name: Install Android SDK Components
        run: |
          source $GITHUB_ENV
          sdkmanager "platform-tools" \
                     "platforms;android-33" \
                     "system-images;android-33;google_apis_playstore;x86_64" \
                     "emulator" \
                     "build-tools;33.0.0"

      # 5. Configurer un AVD pour Pixel 4
      - name: Create AVD
        run: |
          source $GITHUB_ENV
          echo "hw.gpu.mode=swiftshader_indirect" >> $HOME/.android/advancedFeatures.ini
          echo "hw.camera.back=virtualscene" >> $HOME/.android/advancedFeatures.ini
          avdmanager create avd --force --name pixel4_arcore \
                                --package "system-images;android-33;google_apis_playstore;x86_64" \
                                --device "pixel_4"

      # 6. Démarrer l'émulateur
      - name: Start Emulator
        run: |
          source $GITHUB_ENV
          nohup emulator -avd pixel4_arcore -no-window -no-audio -gpu swiftshader_indirect > emulator.log 2>&1 &
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Emulator is ready."

        continue-on-error: true

      - name: Check if Log Exists
        run: ls -l emulator.log || echo "emulator.log not found"     


 # 7. Vérifier les appareils connectés
      - name: Verify Emulator
        run: adb devices

      # 8. Télécharger les journaux de l'émulateur
      - name: Upload Emulator Logs
        if: always()  # S'assure que cette étape est exécutée même si les autres échouent     
        uses: actions/upload-artifact@v3
        with:
          name: emulator-logs
          path: emulator.log
