name: Test ARCore Application

on:
  push:
    branches:
      - main

jobs:
  test-emulator:
    name: Run Android Emulator for ARCore
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: |
            build-tools;33.0.0
            platform-tools
            platforms;android-33

      - name: Configure AVD for Pixel 4
        run: |
          echo "hw.camera.back=virtualscene" >> ~/.android/advancedFeatures.ini
          echo "hw.camera.front=emulated" >> ~/.android/advancedFeatures.ini
          echo "ShowDeviceFrame=yes" >> ~/.android/advancedFeatures.ini
          echo "Pixel2=yes" >> ~/.android/advancedFeatures.ini
          echo "hw.ramSize=1024" >> ~/.android/advancedFeatures.ini
          echo "hw.gpu.enabled=no" >> ~/.android/advancedFeatures.ini

          sdkmanager "system-images;android-33;google_apis;x86_64"
          echo no | avdmanager create avd --force --name test --package "system-images;android-33;google_apis;x86_64" --device "pixel"

      - name: Verify AVD Configuration
        run: |
          cat ~/.android/advancedFeatures.ini
          avdmanager list avd

      - name: Start Emulator
        run: |
          nohup emulator @test -no-window -no-audio -gpu off &
          adb devices
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Emulator is ready"

      - name: Install and Run APK
        run: |
          adb install path/to/your-app.apk
          adb shell am start -n com.example.app/.MainActivity
          adb logcat -d > logcat.txt

      - name: Save Logs
        uses: actions/upload-artifact@v3
        with:
          name: emulator-logs
          path: logcat.txt
