name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: build/app/outputs/flutter-apk/
          key: ${{ runner.os }}-flutter-apk-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-apk-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install Android Command-line Tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Check APK Existence
        run: |
          if [ -f build/app/outputs/flutter-apk/app-release.apk ]; then
            echo "APK already exists. Skipping build."
            exit 0
          else
            echo "APK not found. Proceeding to build."
          fi

      - name: Flutter Clean
        if: ![ -f build/app/outputs/flutter-apk/app-release.apk ]
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

      - name: List build directory contents
        run: ls -R build/app/outputs/flutter-apk/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
